export const NAV = {
  admin: [
    { label: 'Dashboard', path: '/admin' },
    { label: 'Students', path: '/admin/students' },
    { label: 'Teachers', path: '/admin/teachers' },
    { label: 'Departments', path: '/admin/departments' },
    { label: 'Courses', path: '/admin/courses' },
    { label: 'Attendance', path: '/admin/attendance' },
    { label: 'Examinations', path: '/admin/exams' },
    { label: 'Marks & Grades', path: '/admin/marks' },
    { label: 'Results', path: '/admin/results' },
    { label: 'Events', path: '/admin/events' },
    { label: 'University Fests', path: '/admin/fests' },
    { label: 'Cluster Activities', path: '/admin/clusters' },
    { label: 'Sports & Games', path: '/admin/sports' },
    { label: 'Clubs', path: '/admin/clubs' },
    { label: 'Timetable', path: '/admin/timetable' },
    { label: 'Academic Calendar', path: '/admin/calendar' },
    { label: 'Announcements', path: '/admin/announcements' },
    { label: 'Reports', path: '/admin/reports' },
    { label: 'University Information', path: '/admin/university' },
    { label: 'Settings', path: '/admin/settings' },
  ],
  teacher: [
    { label: 'Dashboard', path: '/teacher' },
    { label: 'My Profile', path: '/teacher/profile' },
    { label: 'My Classes', path: '/teacher/classes' },
    { label: 'Students', path: '/teacher/students' },
    { label: 'Attendance', path: '/teacher/attendance' },
    { label: 'Marks', path: '/teacher/marks' },
    { label: 'Results', path: '/teacher/results' },
    { label: 'Timetable', path: '/teacher/timetable' },
    { label: 'Events', path: '/teacher/events' },
    { label: 'Activities', path: '/teacher/activities' },
    { label: 'Announcements', path: '/teacher/announcements' },
  ],
  student: [
    { label: 'Dashboard', path: '/student' },
    { label: 'My Profile', path: '/student/profile' },
    { label: 'My Attendance', path: '/student/attendance' },
    { label: 'My Subjects', path: '/student/subjects' },
    { label: 'My Marks', path: '/student/marks' },
    { label: 'My Grades', path: '/student/grades' },
    { label: 'My Results', path: '/student/results' },
    { label: 'My Timetable', path: '/student/timetable' },
    { label: 'Examinations', path: '/student/exams' },
    { label: 'Events', path: '/student/events' },
    { label: 'Fests', path: '/student/fests' },
    { label: 'Activities', path: '/student/activities' },
    { label: 'Sports', path: '/student/sports' },
    { label: 'Clubs', path: '/student/clubs' },
    { label: 'Announcements', path: '/student/announcements' },
  ],
};
